# Generated by Django 5.1.6 on 2025-02-28 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
