# Generated by Django 5.1.6 on 2025-03-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_attendance_course'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['course', 'student', 'date'], name='home_attend_course__0fb268_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('student', 'course', 'date'), name='unique_attendance'),
        ),
    ]
