# Generated by Django 5.1.6 on 2025-03-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_attendance_home_attend_course__0fb268_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.AddField(
            model_name='course',
            name='departments',
            field=models.ManyToManyField(related_name='courses', to='home.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_general',
            field=models.BooleanField(default=False),
        ),
    ]
