# Generated by Django 5.1.6 on 2025-04-10 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_course_department_course_departments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='previous_level',
            field=models.IntegerField(blank=True, choices=[(100, '100 Level'), (200, '200 Level'), (300, '300 Level'), (400, '400 Level')], null=True),
        ),
    ]
