# Generated by Django 5.1.6 on 2025-04-10 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_student_previous_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='previous_level',
        ),
    ]
