# Generated by Django 5.1.6 on 2025-03-07 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprint', '0003_fingerprintdata_delete_student'),
        ('home', '0010_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fingerprintdata',
            old_name='fingerprint_data',
            new_name='template',
        ),
        migrations.AlterField(
            model_name='fingerprintdata',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student'),
        ),
    ]
